### ISSUE TITLE
Contrast on Minimap highlight is pretty low

### ISSUE THREAD

**Issue by alexanderadam** [sreetamdas/karma#10]
I love your theme so much!
On the only thing that is a bit difficult is the contract on the highlighted part of the Minimap.

Depending on the display it is hard to see what part is actually highlighted.
![Screenshot of VSCode Minimap](https://user-images.githubusercontent.com/372620/149627554-97828d58-ab34-4635-b52d-d8eafde94fbe.png)

Thank you so much for Karma! :raised_hands:

**Comment by sreetamdas** [comment]
@alexanderadam Sorry for the delay here, I'm so glad you like Karma! 💜 

Alright, would the color of the scrollbar (we can also see it in the screenshot) be alright to use there instead? I don't use the minimap so I wasn't aware of this issue—thanks for bringing it up!

Here's what it would look like:

<img width="151" alt="image" src="https://user-images.githubusercontent.com/11270438/156201582-d41c783a-58ca-4e48-b8a2-9e6c027e506e.png">


Additionally, if you wanna use some other custom color for that, you can add this to your `settings.json` for VSCode 😄 

```json
"workbench.colorCustomizations": {
	"[Karma]": {
		"minimapSlider.background": "#ff0000"
	}
}
```

**Comment by alexanderadam** [comment]
Hello @sreetamdas, thank you for your response!

Setting `"minimapSlider.background": "#ff0000"` seems to hide the text.
I have to add a hex value with alpha channel. But then the colour is less intense too.

What colour is currently set? Is it inherited from something?

I just tested a few values and these values are giving me a great contrast ratio on my screens:

```json
{
  "minimapSlider.background": "#ffffff14",
  "minimapSlider.hoverBackground": "#ffffff19",
  "minimapSlider.activeBackground": "#ffffff22",
}
```

**Comment by sreetamdas** [comment]
@alexanderadam I used that color as an example 😅

The exact color being used currently, and in the screenshot above is: `#f7f1ff12`

Lemme know if this color works for you, I'm biased but I think it looks great :)

**Comment by alexanderadam** [comment]
It works, since it contrast is similar to `ffffff14` which I tried in brightness.
Remember to set `hoverBackground` and `activeBackground` to values brighter than `f7f1ff12`. Otherwise it would become less visible on :hover and :active again.

**Comment by sreetamdas** [comment]
Sorry for having dropped the ball on this one, will resume this later this week :)
