### ISSUE TITLE
Styling Bottom Panel Pane Headers and Terminal divider 

### ISSUE THREAD

**Issue by damiankorcz** [sreetamdas/karma#12]
![2022-04-17_04-17-38](https://user-images.githubusercontent.com/7290097/163698830-9a82dbc9-a92a-4319-ae17-12b970843451.gif)

Hi. Great theme! Been using the Lucy theme for some time but since it's been removed from the store I've been looking for a new one and found this. Small issue I've noticed is that styling of the Bottom Panel Pane Headers and Terminal divider doesn't match the theme. I'm not familiar with VSCode theme dev so not sure if you can fix it but I figured filling this issue will at least let you know of it.

**Comment by sreetamdas** [comment]
Sorry for having missed this, I will take care of this. Thanks for bringing it up, and I'm glad you enjoy the theme! 💜
